//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using Smark.Data.Mappings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


namespace Clay.Modules {
    
    
    /// <summary>
    /// Smark.Data Generator Copyright © FanJianHan 2010-2012
    /// website:http://www.ikende.com
    /// </summary>
    [Serializable()]
    [Table()]
    public partial class TextModule : Smark.Data.Mappings.DataObject, ITextModule {
        
        private string mID;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo iD = new Smark.Data.FieldInfo("TextModule", "ID");
        
        private string mTitle;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo title = new Smark.Data.FieldInfo("TextModule", "Title");
        
        private string mHtml;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo html = new Smark.Data.FieldInfo("TextModule", "Html");
        
        [ID()]
        [UID()]
        public virtual string ID {
            get {
                return this.mID;
            }
            set {
                this.mID = value;
                this.EntityState.FieldChange("ID");
            }
        }
        
        [Column()]
        public virtual string Title {
            get {
                return this.mTitle;
            }
            set {
                this.mTitle = value;
                this.EntityState.FieldChange("Title");
            }
        }
        
        [Column()]
        public virtual string Html {
            get {
                return this.mHtml;
            }
            set {
                this.mHtml = value;
                this.EntityState.FieldChange("Html");
            }
        }
    }
    
    /// <summary>
    /// Smark.Data Generator Copyright © FanJianHan 2010-2012
    /// website:http://www.ikende.com
    /// </summary>
    [Serializable()]
    [Table()]
    public partial class ControlLinkText : Smark.Data.Mappings.DataObject, IControlLinkText {
        
        private string mControlID;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo controlID = new Smark.Data.FieldInfo("ControlLinkText", "ControlID");
        
        private string mTextID;
        
        /// <summary>
        /// System.String
        /// </summary>
        public static Smark.Data.FieldInfo textID = new Smark.Data.FieldInfo("ControlLinkText", "TextID");
        
        [Column()]
        public virtual string ControlID {
            get {
                return this.mControlID;
            }
            set {
                this.mControlID = value;
                this.EntityState.FieldChange("ControlID");
            }
        }
        
        [Column()]
        public virtual string TextID {
            get {
                return this.mTextID;
            }
            set {
                this.mTextID = value;
                this.EntityState.FieldChange("TextID");
            }
        }
    }
}
